baseURL = 'https://liem.ca'
languageCode = 'en-us'
title = "Liem Dam-Quang"
theme = "anubis" 
enableEmoji= true
# disqusShortname = 'liem-ca'

[author]
name = "Liem Dam-Quang"

[menu]
	[[menu.main]]
	identifier = "Post"
	url = "/posts/"
	name = "Posts"
	weight = 1

	[[menu.main]]
	identifier = "about"
	url = "/about/"
	name = "About"
	weight = 4

#	[[menu.main]]
#	identifier = "projects"
#	url = "/projects/"
#	name = "Projects"
#	weight = 2

	[[menu.main]]
	identifier = "Categories"
	name = "Categories"
	url = "/categories/"
	weight = 3


[taxonomies]
category = "categories"
tag = "tags"


[params]
	math = true
	author = "Liem Dam-Quang"
	description = "Drilling down the rabbit hole"
	dateFormat = "2006-01-02"
	style = "auto"
	rssAsSocialIcon = true
	copyCodeButton = true
	readNextPosts = 2

[[params.social]]
id = "github"
url = "https://github.com/LiemDQ"

[[params.social]]
id = "linkedin"
url = "https://www.linkedin.com/in/liem-dam-quang/"

[[params.social]]
id = "email"
url = "mailto:liem.daq@gmail.com"

[markup.goldmark.renderer]
unsafe = true