baseURL = 'https://liem.ca'
languageCode = 'en-us'
title = "Striving For Plenty"
theme = "anubis" 
enableEmoji= true
# disqusShortname = 'liem-ca'


[menu]
	[[menu.main]]
	identifier = "Post"
	url = "/posts/"
	name = "Posts"
	weight = 1

	[[menu.main]]
	identifier = "about"
	url = "/about/"
	name = "About"
	weight = 4

#	[[menu.main]]
#	identifier = "projects"
#	url = "/projects/"
#	name = "Projects"
#	weight = 2

	[[menu.main]]
	identifier = "categories"
	name = "Categories"
	url = "/categories/"
	weight = 3


[taxonomies]
category = "categories"
tag = "tags"


[params]
	math = true
	description = "Paradise will be built, not discovered."
	dateFormat = "2006-01-02"
	style = "auto"
	rssAsSocialIcon = true
	copyCodeButton = true
	enableSideNotes = true
	readNextPosts = 4
	readMore = false

	[params.author]
		name = "Liem Dam-Quang"
		email = "dq@liem.ca"

	[[params.social]]
	id = "github"
	url = "https://github.com/LiemDQ"

	[[params.social]]
	id = "linkedin"
	url = "https://www.linkedin.com/in/liem-dam-quang/"

	[[params.social]]
	id = "email"
	url = "mailto:dq@liem.ca"

[caches]
	[caches.images]
		dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe = true